# --- Input ---
arb-dir: lib/l10n
template-arb-file: app_en.arb

# --- Output ---
output-localization-file: app_localizations.dart
output-dir: lib/l10n

# --- Options ---
# !!! أضف هذا السطر لمنع إنشاء الحزمة في .dart_tool
synthetic-package: false
# nullable-getter: false # يمكنك ترك هذا السطر أو إزالته حسب الحاجة